# Generated by Django 2.2.12 on 2020-05-07 16:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=255)),
                ('Created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Movie',
                'verbose_name_plural': 'Movies',
            },
        ),
        migrations.CreateModel(
            name='MovieDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Year', models.CharField(max_length=100)),
                ('Rated', models.CharField(max_length=100)),
                ('Released', models.CharField(max_length=100)),
                ('Runtime', models.CharField(max_length=100)),
                ('Genre', models.CharField(max_length=100)),
                ('Director', models.CharField(max_length=100)),
                ('Writer', models.CharField(max_length=1000)),
                ('Actors', models.CharField(max_length=1000)),
                ('Plot', models.CharField(max_length=1000)),
                ('Language', models.CharField(max_length=100)),
                ('Country', models.CharField(max_length=100)),
                ('Awards', models.CharField(max_length=100)),
                ('Poster', models.CharField(max_length=1000)),
                ('Metascore', models.CharField(max_length=100)),
                ('imdbRating', models.CharField(max_length=100)),
                ('imdbVotes', models.CharField(max_length=100)),
                ('imdbID', models.CharField(max_length=100)),
                ('Type', models.CharField(max_length=100)),
                ('DVD', models.CharField(max_length=100)),
                ('BoxOffice', models.CharField(max_length=100)),
                ('Production', models.CharField(max_length=100)),
                ('Website', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Source', models.CharField(max_length=100)),
                ('Value', models.CharField(max_length=100)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Ratings', to='apis.MovieDetail')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie', to='apis.Movie')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
            },
        ),
    ]
