version: 3

services:
  web:
    restart: always
    build: moviesOMDb
    expose:
      - "8000"
    env_file:
      - env
    environment:
      DEBUG: 'true'
    command: gunicorn movies.wsgi:application -w 2 --bind 0.0.0.0:8000