version: '3'

services:
  web:
    restart: always
    build: moviesOMDb
    expose:
      - "8000"
    ports:
    - "8000:8000"
    environment:
      DEBUG: 'true'
    command: gunicorn movies.wsgi:application -w 2
    depends_on:
      - migration
  migration:
    build: moviesOMDb
    command: python manage.py migrate --noinput
